services:
  - host: http://127.0.0.1:9090
    path: /-/healthy
    name: Prometheus
  # For testing, this configuration is on purpose wrong
  - host: http://127.0.0.1:9090
    path: /health
    name: Prometheus-fail
gotifyHost: http://127.0.0.1:8080
